services:
  ollama:
    restart: always
    devices:
      - "nvidia.com/gpu=all"
    build:
      context: .
      dockerfile: ./docker/ollama.Dockerfile
    networks:
      - backend
  
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    environment:
      OLLAMA_URL: "http://ollama:11434"
    networks:
      - backend
    ports:
      - "8000:8000"

networks:
  backend:
    driver: bridge
